### ISSUE TITLE
arkon

### ISSUE THREAD

**Issue by firstdarsh** [tachiyomiorg/tachiyomi-extensions-1.x#11]
Welcome
I am a tachiyomi user
I like the program a lot and I appreciate your efforts in it. So I have some opinions for you with your permission
first:
Please review the sources because some do not work either incorrectly or do not work in the first place
secondly :
Please return the source AR FlameScans
And with many thanks to you

**Comment by AntsyLich** [comment]
1. Wrong repo
2. This is volunteer work so no guarantee a source will be fixed
3. AR FlameScans exists it's part of Flame Scans extension
