### ISSUE TITLE
Problems rewritten extensions in versions 0.10.12 and earlier

### ISSUE THREAD

**Issue by Raidre** [tachiyomiorg/tachiyomi-extensions-1.x#12]
well i use an old tachiyomi version 0.10.12, because my android is 5.1.1 and the latest version is not supported, so how do i solve the extensions problem in the app

**Comment by arkon** [comment]
Wrong repo, and you already opened an issue: https://github.com/tachiyomiorg/tachiyomi-extensions/issues/12124#issuecomment-1149429053
